# Generated by Django 4.2.13 on 2024-11-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seminar_name', models.CharField(max_length=225)),
                ('seminar_purpose', models.CharField(max_length=225)),
                ('amount_peoples', models.IntegerField()),
                ('seminar_contact', models.CharField(max_length=225)),
            ],
        ),
    ]
