# Generated by Django 4.2.13 on 2024-12-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semidu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='joined_user',
            field=models.IntegerField(null=True),
        ),
    ]
