# Generated by Django 4.2.13 on 2024-12-28 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('semidu', '0002_seminar_joined_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='semiUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='amount_peoples',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='seminar_contact',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='seminar_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='seminar_purpose',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
