# Generated by Django 4.2.13 on 2024-12-29 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('semidu', '0003_seminar_semiuser_alter_seminar_amount_peoples_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrCode', models.ImageField(blank=True, upload_to='qrCode')),
                ('semiInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='semidu.seminar')),
                ('semiUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
