# Generated by Django 4.2.13 on 2024-12-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semidu', '0004_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='r_name',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
