# Generated by Django 4.2.13 on 2024-12-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semidu', '0005_receipt_r_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='qrCode',
        ),
        migrations.AddField(
            model_name='receipt',
            name='qrCD',
            field=models.ImageField(blank=True, upload_to='qrCD'),
        ),
    ]
