# Generated by Django 4.2.13 on 2024-12-29 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semidu', '0006_remove_receipt_qrcode_receipt_qrcd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='semiInfo',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='semiUser',
        ),
    ]
