# Generated by Django 4.2.13 on 2024-12-29 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('semidu', '0007_remove_receipt_semiinfo_remove_receipt_semiuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='r_name',
        ),
        migrations.AddField(
            model_name='receipt',
            name='semInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='semidu.seminar'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='semUs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
