# Generated by Django 4.2.13 on 2024-12-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semidu', '0008_remove_receipt_r_name_receipt_seminfo_receipt_semus'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receiptInfo',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
