# Generated by Django 4.2.13 on 2024-12-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semidu', '0010_seminarq_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='joined_user',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
