# Generated by Django 4.2.13 on 2024-12-31 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('semidu', '0012_alter_review_revuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='semiRevInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='semidu.seminar'),
        ),
        migrations.AlterField(
            model_name='review',
            name='revUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
