# Generated by Django 4.2.13 on 2024-12-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semidu', '0013_review_semirevinfo_alter_review_revuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ratings',
            field=models.IntegerField(null=True),
        ),
    ]
