# Generated by Django 4.2.13 on 2024-12-31 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semidu', '0014_review_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='semidu.receipt'),
        ),
    ]
