# Generated by Django 4.2.13 on 2024-12-31 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semidu', '0016_remove_review_rec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='revName',
        ),
    ]
