# Generated by Django 4.2.13 on 2024-12-31 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semidu', '0017_remove_review_revname'),
    ]

    operations = [
        migrations.CreateModel(
            name='semPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semiMethod', models.CharField(max_length=225, null=True)),
                ('serialNum', models.CharField(max_length=225, null=True)),
                ('semiRelation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='semidu.seminar')),
            ],
        ),
    ]
