# Generated by Django 4.2.13 on 2024-12-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semidu', '0018_sempay'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='seminar_req',
            field=models.CharField(blank=True, default='Free-to-enter', max_length=225),
        ),
    ]
