# Generated by Django 4.2.13 on 2024-12-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semidu', '0019_seminar_seminar_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarq',
            name='reasontoJoin',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='seminarq',
            name='status_req',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='sempay',
            name='payAmount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='seminar_req',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
